### ISSUE TITLE
Add a new fractal to the project!

### ISSUE THREAD

**Issue by smithandrewl** [smithandrewl/fractals#1]
- [x] Sierpinski triangle
- [x] Vicsek
- [x] Vicsekx
- [x] CantorDust
- [x] KochCurve
- [x] KochSnowflake
- [x] Tree
- [x] Sierpinski carpet
- [x] Minkowski sausage
- [x] Dragon curve
- [x] H fractal
- [x] Cesaro

**Comment by matyas94k** [comment]
Please help me with the first run.
I'm using Windows 10 and get this error after sbt run:
java.io.IOException: Cannot run program "which": CreateProcess error=2, The system cannot find the file specified

**Comment by smithandrewl** [comment]
Unfortunately, [scala native does not work on windows as of yet](https://github.com/scala-native/scala-native/issues/113)


Until that issue is resolved, I think it is only possible to run Fractals on Linux or MacOs.

If you you install virtualbox, and install Linux then you can follow the Linux instructions to build it.
